export const data = [
    {
      question: "Which methodology is used to performed Maintenance testing?",
      option1: "Breadth test and depth test",
      option2: "Confirmation testing",
      option3: "Retesting",
      option4: "Sanity testing",
      ans: 1,
    },
    {
      question: "Which of the following is not part of the Test document?",
      option1: "Test Case",
      option2: "Requirements Traceability Matrix [RTM]",
      option3: "Test strategy",
      option4: "Project Initiation Note [PIN]",
      ans: 2,
    },
    {
      question: "Which term is used to define testing?",
      option1: "Evaluating deliverable to find errors",
      option2: "Finding broken code",
      option3: "A stage of all projects",
      option4: "None of the above",
      ans: 1,
    },
    {
      question: "Which of the following is not a valid phase of SDLC (Software Development Life Cycle)?",
      option1: "Testing Phase",
      option2: "Requirement Phase",
      option3: "Deployment phase",
      option4: "Testing closure",
      ans: 4,
    },
    {
      question: "Which of the following testing is also known as white-box testing?",
      option1: "Structural testing",
      option2: "Error guessing technique",
      option3: "Design based testing",
      option4: "None of the above",
      ans: 1,
    },
  {
    question: "unctional testing is a ------?",
      option1: "Test design technique",
      option2: "Test level",
      option3: "SDLC Model",
      option4: "Test type",
      ans: 4,
  },
  {
    question: "What are the different levels of Testing?",
      option1: "Integration testing",
      option2: "Unit testing",
      option3: "System testing",
      option4: "All of the above",
      ans: 4,
  },
  {
    question: "White box testing techniques are?",
      option1: "Statement coverage testing",
      option2: "Decision coverage testing",
      option3: "Data flow testing",
      option4: "All of the above",
      ans: 4,
  },
  {
    question: "In which environment we can performed the Alpha testing?",
      option1: "User's end",
      option2: "Developer's end",
      option3: "User's and developer's end",
      option4: "None of the above",
      ans: 2,
  },
  {
    question: "Exploratory testing is a -----?",
      option1: "Experience-based Test Design Technique",
      option2: "White Box Test Design Technique",
      option3: "Black Box Test Design Technique",
      option4: "Grey Box Test Design Technique",
      ans: 1,
  }
  ];